/**
 * Default icon pack — maps semantic names to @tabler/icons-react.
 * This is the Conduit Classic theme's icon set.
 */

import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowsExchange,
  IconBan,
  IconBold,
  IconBolt,
  IconBug,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconCircleX,
  IconClock,
  IconCloud,
  IconCloudDownload,
  IconCloudOff,
  IconCode,
  IconCopy,
  IconCrown,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDeviceMobile,
  IconDevices,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFingerprint,
  IconFile,
  IconFileCode,
  IconFileImport,
  IconFilePlus,
  IconFileText,
  IconFileX,
  IconFolder,
  IconFolderOpen,
  IconFolderPlus,
  IconH1,
  IconH2,
  IconHammer,
  IconHistory,
  IconHome,
  IconIcons,
  IconInfoCircle,
  IconItalic,
  IconKey,
  IconKeyboard,
  IconLink,
  IconList,
  IconListNumbers,
  IconLoader2,
  IconLock,
  IconLockOpen,
  IconLogin,
  IconLogout,
  IconMail,
  IconMessage,
  IconMessageChatbot,
  IconNetwork,
  IconNotes,
  IconPalette,
  IconPencil,
  IconPhoto,
  IconPinFilled,
  IconPlayerPlay,
  IconPlayerSkipForward,
  IconPlayerStop,
  IconPlayerStopFilled,
  IconPlug,
  IconPlugConnectedX,
  IconPlus,
  IconQrcode,
  IconQuote,
  IconRefresh,
  IconRestore,
  IconRobot,
  IconRocket,
  IconSearch,
  IconSend,
  IconServer,
  IconServer2,
  IconSettings,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconSparkles,
  IconStar,
  IconStarFilled,
  IconStack2,
  IconStrikethrough,
  IconTable,
  IconTag,
  IconTarget,
  IconTerminal,
  IconTerminal2,
  IconTool,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconWifiOff,
  IconWorld,
  IconWorldWww,
  IconX,
} from "@tabler/icons-react";

import type { IconMapping } from "../types";

export const mapping: IconMapping = {
  // ── Actions ──
  close: IconX,
  plus: IconPlus,
  check: IconCheck,
  search: IconSearch,
  trash: IconTrash,
  pencil: IconPencil,
  copy: IconCopy,
  refresh: IconRefresh,
  send: IconSend,
  download: IconDownload,
  upload: IconUpload,
  externalLink: IconExternalLink,
  login: IconLogin,
  logout: IconLogout,
  restore: IconRestore,

  // ── Navigation ──
  home: IconHome,
  arrowLeft: IconArrowLeft,
  arrowRight: IconArrowRight,
  arrowUp: IconArrowUp,
  arrowsExchange: IconArrowsExchange,
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,

  // ── Status ──
  alertCircle: IconAlertCircle,
  alertTriangle: IconAlertTriangle,
  infoCircle: IconInfoCircle,
  circleCheck: IconCircleCheck,
  circleX: IconCircleX,
  ban: IconBan,
  loader: IconLoader2,
  wifiOff: IconWifiOff,

  // ── Security ──
  lock: IconLock,
  lockOpen: IconLockOpen,
  key: IconKey,
  shield: IconShield,
  shieldCheck: IconShieldCheck,
  shieldLock: IconShieldLock,
  fingerprint: IconFingerprint,

  // ── Files & Folders ──
  file: IconFile,
  fileCode: IconFileCode,
  fileImport: IconFileImport,
  filePlus: IconFilePlus,
  fileText: IconFileText,
  fileX: IconFileX,
  folder: IconFolder,
  folderOpen: IconFolderOpen,
  folderPlus: IconFolderPlus,

  // ── People ──
  user: IconUser,
  users: IconUsers,
  crown: IconCrown,

  // ── Connection types ──
  terminal: IconTerminal2,
  terminalAlt: IconTerminal,
  desktop: IconDeviceDesktop,
  globe: IconWorld,
  globeWww: IconWorldWww,
  server: IconServer,
  serverAlt: IconServer2,
  devices: IconDevices,
  deviceMobile: IconDeviceMobile,
  network: IconNetwork,
  plug: IconPlug,
  plugDisconnected: IconPlugConnectedX,

  // ── Favorites ──
  star: IconStar,
  starFilled: IconStarFilled,
  pinFilled: IconPinFilled,

  // ── Data ──
  database: IconDatabase,
  history: IconHistory,
  calendar: IconCalendar,
  clock: IconClock,
  tag: IconTag,
  notes: IconNotes,

  // ── Communication ──
  mail: IconMail,
  message: IconMessage,
  messageChatbot: IconMessageChatbot,

  // ── Cloud ──
  cloud: IconCloud,
  cloudOff: IconCloudOff,
  cloudDownload: IconCloudDownload,

  // ── AI / Automation ──
  robot: IconRobot,
  sparkles: IconSparkles,
  tool: IconTool,
  stack: IconStack2,
  bolt: IconBolt,
  rocket: IconRocket,

  // ── Media / Controls ──
  playerPlay: IconPlayerPlay,
  playerStop: IconPlayerStop,
  playerStopFilled: IconPlayerStopFilled,
  playerSkipForward: IconPlayerSkipForward,

  // ── Input ──
  keyboard: IconKeyboard,
  qrcode: IconQrcode,
  target: IconTarget,

  // ── Appearance ──
  palette: IconPalette,
  icons: IconIcons,
  photo: IconPhoto,

  // ── Misc ──
  hammer: IconHammer,
  bug: IconBug,
  floppy: IconDeviceFloppy,

  // ── Markdown toolbar ──
  bold: IconBold,
  italic: IconItalic,
  strikethrough: IconStrikethrough,
  heading1: IconH1,
  heading2: IconH2,
  link: IconLink,
  code: IconCode,
  list: IconList,
  listNumbers: IconListNumbers,
  table: IconTable,
  quote: IconQuote,

  // ── Missing from audit but in Settings ──
  settings: IconSettings,
  eye: IconEye,
  eyeOff: IconEyeOff,
};
