import {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Ban,
  Bold,
  Bot,
  BotMessageSquare,
  Bug,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  Clock,
  Cloud,
  CloudDownload,
  CloudSync,
  CloudOff,
  Code,
  Columns2,
  Copy,
  Crown,
  Database,
  Download,
  Earth,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileInput,
  FilePlus,
  FileText,
  FileX,
  FingerprintPattern,
  Folder,
  FolderOpen,
  FolderPlus,
  Globe,
  Hammer,
  HardDrive,
  Heading1,
  Heading2,
  History,
  House,
  Image,
  Info,
  Italic,
  Keyboard,
  KeyRound,
  Layers,
  Link,
  List,
  ListOrdered,
  LoaderCircle,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Monitor,
  MonitorSmartphone,
  Network,
  NotepadText,
  Palette,
  Pencil,
  Pin,
  Play,
  Plug,
  Plus,
  QrCode,
  Quote,
  RefreshCw,
  Rocket,
  RotateCcw,
  Rows2,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShieldLock,
  SkipForward,
  Smartphone,
  Sparkles,
  Square,
  SquareTerminal,
  Star,
  Strikethrough,
  Table,
  Tag,
  Target,
  Terminal,
  TextCursor,
  Trash2,
  TriangleAlert,
  Unplug,
  Upload,
  User,
  Users,
  WifiOff,
  Wrench,
  X,
  Zap,
} from "lucide-react";

import type { IconMapping } from "../types";
import { wrapLucide } from "./lucide-wrap";
import { createStateDotIcon } from "./state-dot";

const filled = { filled: true };

export const mapping: IconMapping = {
  // ── Actions ──
  close: wrapLucide(X),
  plus: wrapLucide(Plus),
  check: wrapLucide(Check),
  search: wrapLucide(Search),
  trash: wrapLucide(Trash2),
  pencil: wrapLucide(Pencil),
  copy: wrapLucide(Copy),
  refresh: wrapLucide(RefreshCw),
  send: wrapLucide(Send),
  download: wrapLucide(Download),
  upload: wrapLucide(Upload),
  externalLink: wrapLucide(ExternalLink),
  login: wrapLucide(LogIn),
  logout: wrapLucide(LogOut),
  restore: wrapLucide(RotateCcw),
  settings: wrapLucide(Settings),
  eye: wrapLucide(Eye),
  eyeOff: wrapLucide(EyeOff),

  // ── Navigation ──
  home: wrapLucide(House),
  arrowLeft: wrapLucide(ArrowLeft),
  arrowRight: wrapLucide(ArrowRight),
  arrowUp: wrapLucide(ArrowUp),
  arrowsExchange: wrapLucide(ArrowLeftRight),
  chevronDown: wrapLucide(ChevronDown),
  chevronLeft: wrapLucide(ChevronLeft),
  chevronRight: wrapLucide(ChevronRight),

  // ── Status ──
  alertCircle: wrapLucide(CircleAlert),
  alertTriangle: wrapLucide(TriangleAlert),
  infoCircle: wrapLucide(Info),
  circleCheck: wrapLucide(CircleCheck),
  circleX: wrapLucide(CircleX),
  ban: wrapLucide(Ban),
  loader: wrapLucide(LoaderCircle),
  wifiOff: wrapLucide(WifiOff),

  // ── Security ──
  lock: wrapLucide(Lock),
  lockOpen: wrapLucide(LockOpen),
  key: wrapLucide(KeyRound),
  shield: wrapLucide(Shield),
  shieldCheck: wrapLucide(ShieldCheck),
  shieldLock: wrapLucide(ShieldLock),
  fingerprint: wrapLucide(FingerprintPattern),

  // ── Files & Folders ──
  file: wrapLucide(File),
  fileCode: wrapLucide(FileCode),
  fileImport: wrapLucide(FileInput),
  filePlus: wrapLucide(FilePlus),
  fileText: wrapLucide(FileText),
  fileX: wrapLucide(FileX),
  folder: wrapLucide(Folder),
  folderOpen: wrapLucide(FolderOpen),
  folderPlus: wrapLucide(FolderPlus),

  // ── People ──
  user: wrapLucide(User),
  users: wrapLucide(Users),
  crown: wrapLucide(Crown),

  // ── Connection types ──
  terminal: wrapLucide(SquareTerminal),
  terminalAlt: wrapLucide(Terminal),
  desktop: wrapLucide(Monitor),
  globe: wrapLucide(Globe),
  globeWww: wrapLucide(Earth),
  server: wrapLucide(Server),
  serverAlt: wrapLucide(HardDrive),
  devices: wrapLucide(MonitorSmartphone),
  network: wrapLucide(Network),
  plug: wrapLucide(Plug),
  plugDisconnected: wrapLucide(Unplug),

  // ── Favorites ──
  star: wrapLucide(Star),
  starFilled: wrapLucide(Star, filled),
  pin: wrapLucide(Pin),
  pinFilled: wrapLucide(Pin, filled),

  // ── Data ──
  database: wrapLucide(Database),
  history: wrapLucide(History),
  calendar: wrapLucide(Calendar),
  clock: wrapLucide(Clock),
  tag: wrapLucide(Tag),
  notes: wrapLucide(NotepadText),

  // ── Communication ──
  mail: wrapLucide(Mail),
  message: wrapLucide(MessageSquare),
  messageChatbot: wrapLucide(BotMessageSquare),

  // ── Cloud ──
  cloud: wrapLucide(Cloud),
  cloudOff: wrapLucide(CloudOff),
  cloudDownload: wrapLucide(CloudDownload),
  cloudSync: wrapLucide(CloudSync),

  // ── AI / Automation ──
  robot: wrapLucide(Bot),
  sparkles: wrapLucide(Sparkles),
  tool: wrapLucide(Wrench),
  stack: wrapLucide(Layers),
  bolt: wrapLucide(Zap),
  rocket: wrapLucide(Rocket),

  // ── Media / Controls ──
  playerPlay: wrapLucide(Play),
  playerStop: wrapLucide(Square),
  playerStopFilled: wrapLucide(Square, filled),
  playerSkipForward: wrapLucide(SkipForward),

  // ── Input ──
  keyboard: wrapLucide(Keyboard),
  qrcode: wrapLucide(QrCode),
  target: wrapLucide(Target),

  // ── Appearance ──
  palette: wrapLucide(Palette),
  icons: wrapLucide(Shapes),
  photo: wrapLucide(Image),

  // ── Devices ──
  deviceMobile: wrapLucide(Smartphone),

  // ── Misc ──
  hammer: wrapLucide(Hammer),
  bug: wrapLucide(Bug),
  floppy: wrapLucide(Save),

  // ── Markdown toolbar ──
  bold: wrapLucide(Bold),
  italic: wrapLucide(Italic),
  strikethrough: wrapLucide(Strikethrough),
  heading1: wrapLucide(Heading1),
  heading2: wrapLucide(Heading2),
  link: wrapLucide(Link),
  code: wrapLucide(Code),
  list: wrapLucide(List),
  listNumbers: wrapLucide(ListOrdered),
  table: wrapLucide(Table),
  quote: wrapLucide(Quote),

  // ── Layout and chrome ──
  menu: wrapLucide(Menu),
  splitHorizontal: wrapLucide(Columns2),
  splitVertical: wrapLucide(Rows2),
  ellipsis: wrapLucide(Ellipsis),
  circleFilled: createStateDotIcon("Lucide"),

  // ── Editing ──
  textCursor: wrapLucide(TextCursor),
};
