import {
  X,
  Plus,
  Check,
  MagnifyingGlass,
  Trash,
  PencilSimple,
  Copy,
  ArrowsClockwise,
  PaperPlaneRight,
  DownloadSimple,
  UploadSimple,
  ArrowSquareOut,
  SignIn,
  SignOut,
  ClockCounterClockwise,
  Gear,
  Eye,
  EyeSlash,
  House,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowsLeftRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  WarningCircle,
  Warning,
  Info,
  CheckCircle,
  XCircle,
  Prohibit,
  SpinnerGap,
  WifiSlash,
  Lock,
  LockOpen,
  Key,
  Shield,
  ShieldCheck,
  ShieldWarning,
  Fingerprint,
  File,
  FileCode,
  FileArrowDown,
  FilePlus,
  FileText,
  FileX,
  Folder,
  FolderOpen,
  FolderPlus,
  User,
  Users,
  Crown,
  Terminal,
  TerminalWindow,
  Desktop,
  Globe,
  GlobeSimple,
  HardDrives,
  HardDrive,
  DeviceMobile,
  TreeStructure,
  Plug,
  PlugsConnected,
  Star,
  PushPin,
  Database,
  ClockClockwise,
  Calendar,
  Clock,
  Tag,
  Notepad,
  Envelope,
  ChatCircle,
  ChatCircleDots,
  Cloud,
  CloudSlash,
  CloudArrowDown,
  Robot,
  Sparkle,
  Wrench,
  Stack,
  Lightning,
  Rocket,
  Play,
  Stop,
  SkipForward,
  Keyboard,
  QrCode,
  Crosshair,
  Palette,
  GridFour,
  Image,
  Hammer,
  Bug,
  FloppyDisk,
  TextB,
  TextItalic,
  TextStrikethrough,
  TextHOne,
  TextHTwo,
  Link,
  Code,
  ListBullets,
  ListNumbers,
  Table,
  Quotes,
  ArrowsInLineVertical,
  Circle,
  DotsThree,
  Files,
  List,
  SidebarSimple,
  SquareSplitHorizontal,
  SquareSplitVertical,
  UserCircle,
} from "@phosphor-icons/react";

import { createElement, memo } from "react";
import type { Icon as PhosphorIcon } from "@phosphor-icons/react";
import { iconA11yAttributes } from "../a11y";
import { DEFAULT_ICON_SIZE, type IconComponent, type IconMapping, type IconProps } from "../types";

type Weight = "regular" | "fill";

function wrap(Glyph: PhosphorIcon, weight: Weight = "regular", options: { mirrored?: boolean } = {}): IconComponent {
  const Wrapped = memo(function WrappedPhosphorIcon(props: IconProps) {
    return createElement(Glyph, {
      size: props.size ?? DEFAULT_ICON_SIZE,
      weight,
      mirrored: options.mirrored,
      className: props.className,
      style: props.style,
      ...iconA11yAttributes(props.title),
    });
  });
  Wrapped.displayName = `Phosphor(${Glyph.displayName ?? "icon"})`;
  return Wrapped;
}

const mirrored = { mirrored: true };

export const mapping: IconMapping = {
  // ── Actions ──
  close: wrap(X),
  plus: wrap(Plus),
  check: wrap(Check),
  search: wrap(MagnifyingGlass),
  trash: wrap(Trash),
  pencil: wrap(PencilSimple),
  copy: wrap(Copy),
  refresh: wrap(ArrowsClockwise),
  send: wrap(PaperPlaneRight),
  download: wrap(DownloadSimple),
  upload: wrap(UploadSimple),
  externalLink: wrap(ArrowSquareOut),
  login: wrap(SignIn),
  logout: wrap(SignOut),
  restore: wrap(ClockCounterClockwise),
  settings: wrap(Gear),
  eye: wrap(Eye),
  eyeOff: wrap(EyeSlash),

  // ── Navigation ──
  home: wrap(House),
  arrowLeft: wrap(ArrowLeft),
  arrowRight: wrap(ArrowRight),
  arrowUp: wrap(ArrowUp),
  arrowsExchange: wrap(ArrowsLeftRight),
  chevronDown: wrap(CaretDown),
  chevronLeft: wrap(CaretLeft),
  chevronRight: wrap(CaretRight),

  // ── Status ──
  alertCircle: wrap(WarningCircle),
  alertTriangle: wrap(Warning),
  infoCircle: wrap(Info),
  circleCheck: wrap(CheckCircle),
  circleX: wrap(XCircle),
  ban: wrap(Prohibit),
  loader: wrap(SpinnerGap),
  wifiOff: wrap(WifiSlash),

  // ── Security ──
  lock: wrap(Lock),
  lockOpen: wrap(LockOpen),
  key: wrap(Key),
  shield: wrap(Shield),
  shieldCheck: wrap(ShieldCheck),
  shieldLock: wrap(ShieldWarning),
  fingerprint: wrap(Fingerprint),

  // ── Files & Folders ──
  file: wrap(File),
  fileCode: wrap(FileCode),
  fileImport: wrap(FileArrowDown),
  filePlus: wrap(FilePlus),
  fileText: wrap(FileText),
  fileX: wrap(FileX),
  folder: wrap(Folder),
  folderOpen: wrap(FolderOpen),
  folderPlus: wrap(FolderPlus),

  // ── People ──
  user: wrap(User),
  users: wrap(Users),
  crown: wrap(Crown),

  // ── Connection types ──
  terminal: wrap(TerminalWindow),
  terminalAlt: wrap(Terminal),
  desktop: wrap(Desktop),
  globe: wrap(Globe),
  globeWww: wrap(GlobeSimple),
  server: wrap(HardDrive),
  serverAlt: wrap(HardDrives),
  devices: wrap(DeviceMobile),
  deviceMobile: wrap(DeviceMobile),
  network: wrap(TreeStructure),
  plug: wrap(Plug),
  plugDisconnected: wrap(PlugsConnected),

  // ── Favorites ──
  star: wrap(Star),
  starFilled: wrap(Star, "fill"),
  pin: wrap(PushPin),
  pinFilled: wrap(PushPin, "fill"),

  // ── Data ──
  database: wrap(Database),
  history: wrap(ClockClockwise),
  calendar: wrap(Calendar),
  clock: wrap(Clock),
  tag: wrap(Tag),
  notes: wrap(Notepad),

  // ── Communication ──
  mail: wrap(Envelope),
  message: wrap(ChatCircle),
  messageChatbot: wrap(ChatCircleDots),

  // ── Cloud ──
  cloud: wrap(Cloud),
  cloudOff: wrap(CloudSlash),
  cloudDownload: wrap(CloudArrowDown),

  // ── AI / Automation ──
  robot: wrap(Robot),
  sparkles: wrap(Sparkle),
  tool: wrap(Wrench),
  stack: wrap(Stack),
  bolt: wrap(Lightning),
  rocket: wrap(Rocket),

  // ── Media / Controls ──
  playerPlay: wrap(Play),
  playerStop: wrap(Stop),
  playerStopFilled: wrap(Stop, "fill"),
  playerSkipForward: wrap(SkipForward),

  // ── Input ──
  keyboard: wrap(Keyboard),
  qrcode: wrap(QrCode),
  target: wrap(Crosshair),

  // ── Appearance ──
  palette: wrap(Palette),
  icons: wrap(GridFour),
  photo: wrap(Image),

  // ── Misc ──
  hammer: wrap(Hammer),
  bug: wrap(Bug),
  floppy: wrap(FloppyDisk),

  // ── Markdown toolbar ──
  bold: wrap(TextB),
  italic: wrap(TextItalic),
  strikethrough: wrap(TextStrikethrough),
  heading1: wrap(TextHOne),
  heading2: wrap(TextHTwo),
  link: wrap(Link),
  code: wrap(Code),
  list: wrap(ListBullets),
  listNumbers: wrap(ListNumbers),
  table: wrap(Table),
  quote: wrap(Quotes),

  // ── Layout and chrome ──
  menu: wrap(List),
  panelLeft: wrap(SidebarSimple, "fill"),
  panelLeftOff: wrap(SidebarSimple),
  panelRight: wrap(SidebarSimple, "fill", mirrored),
  panelRightOff: wrap(SidebarSimple, "regular", mirrored),
  splitHorizontal: wrap(SquareSplitHorizontal),
  splitVertical: wrap(SquareSplitVertical),
  ellipsis: wrap(DotsThree),
  collapseAll: wrap(ArrowsInLineVertical),
  account: wrap(UserCircle),
  explorer: wrap(Files),
  circleFilled: wrap(Circle, "fill"),
};
