import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsExchange,
  IconArrowUp,
  IconBan,
  IconBold,
  IconBolt,
  IconBug,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconCircleX,
  IconClock,
  IconCloud,
  IconCloudDownload,
  IconCloudOff,
  IconCode,
  IconCopy,
  IconCrown,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDeviceMobile,
  IconDevices,
  IconDots,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileCode,
  IconFileImport,
  IconFilePlus,
  IconFileText,
  IconFileX,
  IconFingerprint,
  IconFolder,
  IconFolderOpen,
  IconFolderPlus,
  IconH1,
  IconH2,
  IconHammer,
  IconHistory,
  IconHome,
  IconIcons,
  IconInfoCircle,
  IconItalic,
  IconKey,
  IconKeyboard,
  IconLayoutColumns,
  IconLayoutRows,
  IconLink,
  IconList,
  IconListNumbers,
  IconLoader2,
  IconLock,
  IconLockOpen,
  IconLogin,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMessage,
  IconMessageChatbot,
  IconNetwork,
  IconNotes,
  IconPalette,
  IconPencil,
  IconPhoto,
  IconPin,
  IconPinFilled,
  IconPlayerPlay,
  IconPlayerSkipForward,
  IconPlayerStop,
  IconPlayerStopFilled,
  IconPlug,
  IconPlugConnectedX,
  IconPlus,
  IconQrcode,
  IconQuote,
  IconRefresh,
  IconRestore,
  IconRobot,
  IconRocket,
  IconSearch,
  IconSend,
  IconServer,
  IconServer2,
  IconSettings,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconSparkles,
  IconStack2,
  IconStar,
  IconStarFilled,
  IconStrikethrough,
  IconTable,
  IconTag,
  IconTarget,
  IconTerminal,
  IconTerminal2,
  IconTool,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconWifiOff,
  IconWorld,
  IconWorldWww,
  IconX,
} from "@tabler/icons-react";

import { createElement, memo, type ComponentType } from "react";
import type { IconProps as TablerIconProps } from "@tabler/icons-react";
import { iconA11yAttributes } from "../a11y";
import { DEFAULT_ICON_SIZE, type IconComponent, type IconMapping, type IconProps } from "../types";
import { createStateDotIcon } from "./state-dot";

const TABLER_STROKE_WIDTH = 1.5;

function wrap(TablerIcon: ComponentType<TablerIconProps>): IconComponent {
  const Wrapped = memo(function WrappedTablerIcon(props: IconProps) {
    return createElement(TablerIcon, {
      size: props.size ?? DEFAULT_ICON_SIZE,
      stroke: props.stroke ?? TABLER_STROKE_WIDTH,
      className: props.className,
      style: props.style,
      ...iconA11yAttributes(props.title),
    });
  });
  Wrapped.displayName = `Tabler(${TablerIcon.displayName ?? "icon"})`;
  return Wrapped;
}

export const mapping: IconMapping = {
  // ── Actions ──
  close: wrap(IconX),
  plus: wrap(IconPlus),
  check: wrap(IconCheck),
  search: wrap(IconSearch),
  trash: wrap(IconTrash),
  pencil: wrap(IconPencil),
  copy: wrap(IconCopy),
  refresh: wrap(IconRefresh),
  send: wrap(IconSend),
  download: wrap(IconDownload),
  upload: wrap(IconUpload),
  externalLink: wrap(IconExternalLink),
  login: wrap(IconLogin),
  logout: wrap(IconLogout),
  restore: wrap(IconRestore),
  settings: wrap(IconSettings),
  eye: wrap(IconEye),
  eyeOff: wrap(IconEyeOff),

  // ── Navigation ──
  home: wrap(IconHome),
  arrowLeft: wrap(IconArrowLeft),
  arrowRight: wrap(IconArrowRight),
  arrowUp: wrap(IconArrowUp),
  arrowsExchange: wrap(IconArrowsExchange),
  chevronDown: wrap(IconChevronDown),
  chevronLeft: wrap(IconChevronLeft),
  chevronRight: wrap(IconChevronRight),

  // ── Status ──
  alertCircle: wrap(IconAlertCircle),
  alertTriangle: wrap(IconAlertTriangle),
  infoCircle: wrap(IconInfoCircle),
  circleCheck: wrap(IconCircleCheck),
  circleX: wrap(IconCircleX),
  ban: wrap(IconBan),
  loader: wrap(IconLoader2),
  wifiOff: wrap(IconWifiOff),

  // ── Security ──
  lock: wrap(IconLock),
  lockOpen: wrap(IconLockOpen),
  key: wrap(IconKey),
  shield: wrap(IconShield),
  shieldCheck: wrap(IconShieldCheck),
  shieldLock: wrap(IconShieldLock),
  fingerprint: wrap(IconFingerprint),

  // ── Files & Folders ──
  file: wrap(IconFile),
  fileCode: wrap(IconFileCode),
  fileImport: wrap(IconFileImport),
  filePlus: wrap(IconFilePlus),
  fileText: wrap(IconFileText),
  fileX: wrap(IconFileX),
  folder: wrap(IconFolder),
  folderOpen: wrap(IconFolderOpen),
  folderPlus: wrap(IconFolderPlus),

  // ── People ──
  user: wrap(IconUser),
  users: wrap(IconUsers),
  crown: wrap(IconCrown),

  // ── Connection types ──
  terminal: wrap(IconTerminal2),
  terminalAlt: wrap(IconTerminal),
  desktop: wrap(IconDeviceDesktop),
  globe: wrap(IconWorld),
  globeWww: wrap(IconWorldWww),
  server: wrap(IconServer),
  serverAlt: wrap(IconServer2),
  devices: wrap(IconDevices),
  deviceMobile: wrap(IconDeviceMobile),
  network: wrap(IconNetwork),
  plug: wrap(IconPlug),
  plugDisconnected: wrap(IconPlugConnectedX),

  // ── Favorites ──
  star: wrap(IconStar),
  starFilled: wrap(IconStarFilled),
  pin: wrap(IconPin),
  pinFilled: wrap(IconPinFilled),

  // ── Data ──
  database: wrap(IconDatabase),
  history: wrap(IconHistory),
  calendar: wrap(IconCalendar),
  clock: wrap(IconClock),
  tag: wrap(IconTag),
  notes: wrap(IconNotes),

  // ── Communication ──
  mail: wrap(IconMail),
  message: wrap(IconMessage),
  messageChatbot: wrap(IconMessageChatbot),

  // ── Cloud ──
  cloud: wrap(IconCloud),
  cloudOff: wrap(IconCloudOff),
  cloudDownload: wrap(IconCloudDownload),

  // ── AI / Automation ──
  robot: wrap(IconRobot),
  sparkles: wrap(IconSparkles),
  tool: wrap(IconTool),
  stack: wrap(IconStack2),
  bolt: wrap(IconBolt),
  rocket: wrap(IconRocket),

  // ── Media / Controls ──
  playerPlay: wrap(IconPlayerPlay),
  playerStop: wrap(IconPlayerStop),
  playerStopFilled: wrap(IconPlayerStopFilled),
  playerSkipForward: wrap(IconPlayerSkipForward),

  // ── Input ──
  keyboard: wrap(IconKeyboard),
  qrcode: wrap(IconQrcode),
  target: wrap(IconTarget),

  // ── Appearance ──
  palette: wrap(IconPalette),
  icons: wrap(IconIcons),
  photo: wrap(IconPhoto),

  // ── Misc ──
  hammer: wrap(IconHammer),
  bug: wrap(IconBug),
  floppy: wrap(IconDeviceFloppy),

  // ── Markdown toolbar ──
  bold: wrap(IconBold),
  italic: wrap(IconItalic),
  strikethrough: wrap(IconStrikethrough),
  heading1: wrap(IconH1),
  heading2: wrap(IconH2),
  link: wrap(IconLink),
  code: wrap(IconCode),
  list: wrap(IconList),
  listNumbers: wrap(IconListNumbers),
  table: wrap(IconTable),
  quote: wrap(IconQuote),

  // ── Layout and chrome ──
  menu: wrap(IconMenu2),
  splitHorizontal: wrap(IconLayoutColumns),
  splitVertical: wrap(IconLayoutRows),
  ellipsis: wrap(IconDots),
  circleFilled: createStateDotIcon("Tabler"),
};
