/**
 * Agent instruction file writer — generates ~/.claude/CLAUDE.md and ~/.codex/AGENTS.md
 * on every app launch so external agents know about Conduit's MCP tools.
 *
 * Uses marker-based sections to preserve user content in existing files.
 */

import { app } from 'electron';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { getSocketPath, getEnvConfig, getDataDir } from './env-config.js';
import { getExternalClaudeMd, getExternalAgentsMd } from './ai/instructions.js';

const MARKER_START = '<!-- conduit-managed-start -->';
const MARKER_END = '<!-- conduit-managed-end -->';
const GENERATED_BY = 'Generated by Conduit';

function getMcpServerPath(): string {
  if (app.isPackaged) {
    return path.join(process.resourcesPath, 'mcp', 'dist', 'index.js');
  }
  return path.resolve(app.getAppPath(), 'mcp', 'dist', 'index.js');
}

function buildManagedSection(content: string, version: string): string {
  return [
    MARKER_START,
    `<!-- ${GENERATED_BY} v${version} — do not edit this section -->`,
    content,
    MARKER_END,
  ].join('\n');
}

/**
 * Write a managed section into a file, preserving any user content.
 *
 * - File doesn't exist → create with managed content
 * - File has markers → replace between markers
 * - File exists without markers → append managed section
 *   (secondary check for stale "Generated by Conduit" text prevents duplicate appends)
 */
function writeManagedFile(filePath: string, managedSection: string): void {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, managedSection + '\n', 'utf-8');
    console.log(`[agent-instructions] Created ${filePath}`);
    return;
  }

  const existing = fs.readFileSync(filePath, 'utf-8');
  const startIdx = existing.indexOf(MARKER_START);
  const endIdx = existing.indexOf(MARKER_END);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Replace existing managed section
    const before = existing.substring(0, startIdx);
    const after = existing.substring(endIdx + MARKER_END.length);
    fs.writeFileSync(filePath, before + managedSection + after, 'utf-8');
    console.log(`[agent-instructions] Updated managed section in ${filePath}`);
    return;
  }

  // No markers — check for stale generated content to avoid duplicate appends
  if (existing.includes(GENERATED_BY)) {
    // Stale content exists but without proper markers. Replace the whole
    // "# Conduit MCP Integration" section if found, otherwise skip.
    const sectionIdx = existing.indexOf('# Conduit MCP Integration');
    if (sectionIdx !== -1) {
      const before = existing.substring(0, sectionIdx).trimEnd();
      fs.writeFileSync(filePath, before + '\n\n' + managedSection + '\n', 'utf-8');
      console.log(`[agent-instructions] Replaced stale section in ${filePath}`);
      return;
    }
    // Can't safely replace — skip to avoid corruption
    console.log(`[agent-instructions] Skipping ${filePath} (stale content but can't locate section)`);
    return;
  }

  // Append to existing file
  const separator = existing.endsWith('\n') ? '\n' : '\n\n';
  fs.writeFileSync(filePath, existing + separator + managedSection + '\n', 'utf-8');
  console.log(`[agent-instructions] Appended managed section to ${filePath}`);
}

const execFileAsync = promisify(execFile);

async function isCodexAvailable(): Promise<boolean> {
  const codexDir = path.join(os.homedir(), '.codex');
  if (fs.existsSync(codexDir)) return true;

  try {
    await execFileAsync('which', ['codex']);
    return true;
  } catch {
    return false;
  }
}

/**
 * Write agent instruction files. Called on every app launch.
 * Non-blocking, best-effort — errors are logged but not thrown.
 */
export async function writeAgentInstructions(): Promise<void> {
  const version = app.getVersion();
  const mcpServerPath = getMcpServerPath();
  const socketPath = getSocketPath();
  const conduitEnv = getEnvConfig().environment;

  const opts = { mcpServerPath, socketPath, conduitEnv };

  const claudeContent = getExternalClaudeMd(opts);
  const claudeManaged = buildManagedSection(claudeContent, version);

  // Write ~/.claude/CLAUDE.md (global — external terminal usage)
  try {
    const claudeMdPath = path.join(os.homedir(), '.claude', 'CLAUDE.md');
    writeManagedFile(claudeMdPath, claudeManaged);
  } catch (err) {
    console.warn('[agent-instructions] Failed to write global CLAUDE.md:', err);
  }

  // Write CLAUDE.md into the SDK agent working directory (project-level)
  try {
    const agentDir = path.join(getDataDir(), 'agent', 'claude-code');
    fs.mkdirSync(agentDir, { recursive: true });
    const localClaudeMd = path.join(agentDir, 'CLAUDE.md');
    writeManagedFile(localClaudeMd, claudeManaged);
  } catch (err) {
    console.warn('[agent-instructions] Failed to write agent CLAUDE.md:', err);
  }

  // Write Codex files (only if Codex is available)
  try {
    if (await isCodexAvailable()) {
      const codexContent = getExternalAgentsMd(opts);
      const codexManaged = buildManagedSection(codexContent, version);

      // Write ~/.codex/AGENTS.md (global — external terminal usage)
      const agentsMdPath = path.join(os.homedir(), '.codex', 'AGENTS.md');
      writeManagedFile(agentsMdPath, codexManaged);

      // Write AGENTS.md into the SDK agent working directory (project-level)
      const agentDir = path.join(getDataDir(), 'agent', 'codex');
      fs.mkdirSync(agentDir, { recursive: true });
      const localAgentsMd = path.join(agentDir, 'AGENTS.md');
      writeManagedFile(localAgentsMd, codexManaged);
    }
  } catch (err) {
    console.warn('[agent-instructions] Failed to write AGENTS.md:', err);
  }
}
