import { describe, it, expect, beforeEach, afterEach, afterAll, vi } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const FAKE_HOME = fs.mkdtempSync(path.join(os.tmpdir(), 'conduit-fake-home-'));
const FAKE_USER_DATA = fs.mkdtempSync(path.join(os.tmpdir(), 'conduit-fake-userdata-'));

vi.mock('electron', () => ({
  app: {
    isPackaged: false,
    getVersion: () => '0.0.0-test',
    getAppPath: () => '/tmp/conduit-test-app',
    getPath: () => FAKE_USER_DATA,
  },
}));

vi.mock('node:os', async (importOriginal) => {
  const actual = await importOriginal<typeof import('node:os')>();
  return { ...actual, default: { ...actual, homedir: () => FAKE_HOME }, homedir: () => FAKE_HOME };
});

const { removeManagedSection, writeAgentInstructions } = await import('../agent-instructions.js');

const MARKER_START = '<!-- conduit-managed-start -->';
const MARKER_END = '<!-- conduit-managed-end -->';

const MANAGED = [
  MARKER_START,
  '<!-- Generated by Conduit v0.0.0 — do not edit this section -->',
  '# Conduit MCP Integration',
  '',
  'Tool reference goes here.',
  MARKER_END,
].join('\n');

let tmpDir: string;
let filePath: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'conduit-agent-instructions-'));
  filePath = path.join(tmpDir, 'CLAUDE.md');
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

afterAll(() => {
  fs.rmSync(FAKE_HOME, { recursive: true, force: true });
  fs.rmSync(FAKE_USER_DATA, { recursive: true, force: true });
});

describe('removeManagedSection', () => {
  it('strips the managed block and keeps surrounding user content', () => {
    const userBefore = '# Global Claude Rules\n\nBe concise.';
    const userAfter = '## Attributions\n\nNo AI footers.';
    fs.writeFileSync(filePath, `${userBefore}\n\n${MANAGED}\n\n${userAfter}\n`, 'utf-8');

    removeManagedSection(filePath);

    expect(fs.readFileSync(filePath, 'utf-8')).toBe(`${userBefore}\n\n${userAfter}\n`);
  });

  it('leaves a file with no markers completely untouched', () => {
    const original = '# Global Claude Rules\n\n# Conduit MCP Integration\n\nHand written.\n';
    fs.writeFileSync(filePath, original, 'utf-8');

    removeManagedSection(filePath);

    expect(fs.readFileSync(filePath, 'utf-8')).toBe(original);
  });

  it('is idempotent across repeated launches', () => {
    fs.writeFileSync(filePath, `# Rules\n\n${MANAGED}\n`, 'utf-8');

    removeManagedSection(filePath);
    const afterFirst = fs.readFileSync(filePath, 'utf-8');
    removeManagedSection(filePath);

    expect(fs.readFileSync(filePath, 'utf-8')).toBe(afterFirst);
    expect(afterFirst).toBe('# Rules\n');
  });

  it('empties a file that held only the managed block', () => {
    fs.writeFileSync(filePath, `${MANAGED}\n`, 'utf-8');

    removeManagedSection(filePath);

    expect(fs.readFileSync(filePath, 'utf-8')).toBe('');
  });

  it('keeps user content that sits only above the block', () => {
    fs.writeFileSync(filePath, `# Rules\n\nBe concise.\n\n${MANAGED}\n`, 'utf-8');

    removeManagedSection(filePath);

    expect(fs.readFileSync(filePath, 'utf-8')).toBe('# Rules\n\nBe concise.\n');
  });

  it('does nothing when the file does not exist', () => {
    expect(() => removeManagedSection(path.join(tmpDir, 'missing.md'))).not.toThrow();
    expect(fs.existsSync(path.join(tmpDir, 'missing.md'))).toBe(false);
  });
});

describe('writeAgentInstructions', () => {
  const globalClaudeMd = path.join(FAKE_HOME, '.claude', 'CLAUDE.md');
  const globalAgentsMd = path.join(FAKE_HOME, '.codex', 'AGENTS.md');
  // getDataDir() = {userData}/conduit-dev when unpackaged (preview env)
  const agentClaudeMd = path.join(FAKE_USER_DATA, 'conduit-dev', 'agent', 'claude-code', 'CLAUDE.md');

  beforeEach(() => {
    fs.rmSync(path.join(FAKE_HOME, '.claude'), { recursive: true, force: true });
    fs.rmSync(path.join(FAKE_HOME, '.codex'), { recursive: true, force: true });
    fs.rmSync(path.join(FAKE_USER_DATA, 'conduit-dev'), { recursive: true, force: true });
  });

  it('writes the tool reference into the agent working directory', async () => {
    await writeAgentInstructions();

    const written = fs.readFileSync(agentClaudeMd, 'utf-8');
    expect(written).toContain(MARKER_START);
    expect(written).toContain('# Conduit MCP Integration');
    expect(written).toContain('connection_list');
  });

  it('never creates the global instruction files', async () => {
    await writeAgentInstructions();

    expect(fs.existsSync(globalClaudeMd)).toBe(false);
    expect(fs.existsSync(globalAgentsMd)).toBe(false);
  });

  it('strips a legacy managed section from the global files, keeping user rules', async () => {
    fs.mkdirSync(path.join(FAKE_HOME, '.claude'), { recursive: true });
    fs.mkdirSync(path.join(FAKE_HOME, '.codex'), { recursive: true });
    fs.writeFileSync(globalClaudeMd, `# My Rules\n\nBe brief.\n\n${MANAGED}\n`, 'utf-8');
    fs.writeFileSync(globalAgentsMd, `# My Agents\n\n${MANAGED}\n`, 'utf-8');

    await writeAgentInstructions();

    expect(fs.readFileSync(globalClaudeMd, 'utf-8')).toBe('# My Rules\n\nBe brief.\n');
    expect(fs.readFileSync(globalAgentsMd, 'utf-8')).toBe('# My Agents\n');
  });

  it('stays stable across repeated launches', async () => {
    fs.mkdirSync(path.join(FAKE_HOME, '.claude'), { recursive: true });
    fs.writeFileSync(globalClaudeMd, `# My Rules\n\n${MANAGED}\n`, 'utf-8');

    await writeAgentInstructions();
    const globalAfterFirst = fs.readFileSync(globalClaudeMd, 'utf-8');
    const agentAfterFirst = fs.readFileSync(agentClaudeMd, 'utf-8');

    await writeAgentInstructions();

    expect(fs.readFileSync(globalClaudeMd, 'utf-8')).toBe(globalAfterFirst);
    expect(fs.readFileSync(agentClaudeMd, 'utf-8')).toBe(agentAfterFirst);
  });

  it('leaves a Codex-style file with no markers alone', () => {
    const agentsMd = path.join(tmpDir, 'AGENTS.md');
    const original = '# My agents\n\nDo the thing.\n';
    fs.writeFileSync(agentsMd, original, 'utf-8');

    removeManagedSection(agentsMd);

    expect(fs.readFileSync(agentsMd, 'utf-8')).toBe(original);
  });

  it('ignores a truncated block missing its end marker', () => {
    const original = `# Rules\n\n${MARKER_START}\n# Conduit MCP Integration\n`;
    fs.writeFileSync(filePath, original, 'utf-8');

    removeManagedSection(filePath);

    expect(fs.readFileSync(filePath, 'utf-8')).toBe(original);
  });
});
